pipeline:
  name: Build engineering-workstation
  identifier: Build_daniel_c_trainor_engineering_workstation_1786565840099
  projectIdentifier: Engineering_Workstation_CI
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1786565397777
        repoName: daniel-c-trainor/engineering-workstation
        build: <+input>
