pipeline:
  name: Build engineering-workstation
  identifier: Build_daniel_c_trainor_engineering_workstation_1786565840099
  projectIdentifier: Engineering_Workstation_CI
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: Run
                  name: Install Python Dependencies
                  identifier: Install_Python_Dependencies
                  spec:
                    shell: Sh
                    command: |-
                      python3 -m pip install --upgrade pip
                      pip install -e .
                      pip install pytest pytest-cov
                      pip install ruff
              - step:
                  type: Run
                  name: Ruff Lint
                  identifier: Ruff_Lint
                  spec:
                    shell: Sh
                    command: ruff check .
              - step:
                  type: Run
                  name: Run Tests and Coverage
                  identifier: Run_Tests_and_Coverage
                  spec:
                    shell: Sh
                    command: |-
                      export PYTHONPATH="${PYTHONPATH}:/harness"
                      pytest --cov=src --cov-report=xml
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1786565397777
        repoName: daniel-c-trainor/engineering-workstation
        build: <+input>
